trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - pipelines/scenario1/*
    
pool:
  vmImage: ubuntu-latest

steps:

# Archive Website Files

- task: ArchiveFiles@2
  displayName: Archive Website Files
  inputs:
    rootFolderOrFile: 'Socksify-Project'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/socksify.zip'
    replaceExistingArchive: true

# Publish Artifact

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'