trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:

# Show files for debugging

- script: |
    pwd
    ls -R
  displayName: Show Repository Files

# Archive Files

- task: ArchiveFiles@2
  displayName: Archive Website Files
  inputs:
    rootFolderOrFile: '.'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/socksify.zip'
    replaceExistingArchive: true

# Publish Artifact

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'