trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - pipelines/scenario1/* 
    

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.5.7'

steps:

# Install Terraform

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: $(terraformVersion)

# Terraform Init

- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'terraform'
    backendServiceArm: 'azure-sub1'
    backendAzureRmResourceGroupName: 'devop-backend'
    backendAzureRmStorageAccountName: 'devopstorage001'
    backendAzureRmContainerName: 'blobdevops'
    backendAzureRmKey: 'terraform.tfstate'

# Terraform Plan

- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'terraform'
    environmentServiceNameAzureRM: 'azure-sub1'

# Terraform Apply

- task: TerraformTaskV4@4
  displayName: Terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'terraform'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'azure-sub1'